version: '3.7'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
      POSTGRES_DB: n8ndb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  n8n:
    build: .
    ports:
      - "5680:5680"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8ndb
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8npass
      N8N_BASIC_AUTH_ACTIVE: 'true'
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: adminpass
      N8N_HOST: n8n-drake.appdrake.ch
      N8N_PORT: 5680
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
